### PR TITLE
URA-113 Somalier workflow v 1 0 0

### PR DESCRIPTION
**Pull request by Aisha-D**
- Generic somalier workflow applicable to any pipeline with somalier files outputted from somalier_extract

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @jethror1)

___
*[`README.md` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1#-N1n2Qx695SLn6H3hiel:-N1n2Qx695SLn6H3hiem:b-dltz7d) ([raw file](https://github.com/eastgenomics/eggd_somalier_workflow/blob/8e5c18f5bd3be8464eed6909d3bce62aa27f9067/README.md#L4)):*
> ```Markdown
> 
> DNAnexus somalier workflow applicable to any pipeline which has somalier
> output files from somalier_extract. The outputs of this workflow
> ```

can this be a link for niceness? [somalier_extract](https://github.com/eastgenomics/eggd_somalier_extract) should work

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Aisha-D, @jethror1, and @woook)

___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1#-N1n317U2V5UeNI4wC2H:-N1n317U2V5UeNI4wC2I:b60c579) ([raw file](https://github.com/eastgenomics/eggd_somalier_workflow/blob/8e5c18f5bd3be8464eed6909d3bce62aa27f9067/README.md#L15)):*
> ```Markdown
> 
> The threshold to predict female sex phenotype is currently set to
> 70 which is the case where all SNPs of X chromosome are present. If this
> ```

Clarify wording please



_Code quote:_
```Markdown
The threshold to predict female sex phenotype is currently set to
70 which is the case where all SNPs of X chromosome are present. If this
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @woook)

___
*[`README.md` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1#-N1n2Qx695SLn6H3hiel:-N1n8lym0pPKP6wVZYPk:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_workflow/blob/8e5c18f5bd3be8464eed6909d3bce62aa27f9067/README.md#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can this be a link for niceness? [somalier_extract](https://github.com/eastgenomics/eggd_somalier_extract) should work
</blockquote></details>

Done.
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1#-N1n317U2V5UeNI4wC2H:-N1n8meF9U6kuEhE0KCm:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_workflow/blob/8e5c18f5bd3be8464eed6909d3bce62aa27f9067/README.md#L15)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Clarify wording please
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @woook)

**Review by woook — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_workflow/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
